/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ttt.h"

bool_t
xdr_play_args (XDR *xdrs, play_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->row))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->column))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->player))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_simbol (XDR *xdrs, simbol *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->simbol0))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->simbol1))
		 return FALSE;
	return TRUE;
}
